version: "3.8"

services:
    travel-buddy:
        image: metakgporg/travel-buddy-app
        container_name: travel-buddy-app
        build: .
        restart: always
        env_file:
            - .env
        networks:
            metaploy-network:
                aliases:
                    - travel-buddy
        volumes:
            - nginx-config-volume:/etc/nginx/sites-enabled
        logging:
            driver: "json-file"
            options:
                max-size: "100m"
                max-file: "3"

networks:
    metaploy-network:
        external: true
        name: metaploy-network

volumes:
    nginx-config-volume:
        external: true
        name: metaploy-nginx-config-volume
